// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttwosOqqg5vie8vvU9oUYZ0HIh7cIIoI',
    appId: '1:664445745917:android:60c8fa298d881678365c94',
    messagingSenderId: '664445745917',
    projectId: 'vocabularies-kroatic',
    storageBucket: 'vocabularies-kroatic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQLqG9T7h9-x3SML88ktQZNKkrWNOpFU',
    appId: '1:664445745917:ios:3fb07696ed434457365c94',
    messagingSenderId: '664445745917',
    projectId: 'vocabularies-kroatic',
    storageBucket: 'vocabularies-kroatic.firebasestorage.app',
    iosBundleId: 'com.vochr.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqH5DzqWy-loWSlMHmqDCyJ4cjZVZSH8s',
    appId: '1:664445745917:web:22f3d3868c8f074c365c94',
    messagingSenderId: '664445745917',
    projectId: 'vocabularies-kroatic',
    authDomain: 'vocabularies-kroatic.firebaseapp.com',
    storageBucket: 'vocabularies-kroatic.firebasestorage.app',
  );

}