import 'package:flutter/material.dart';

/// Statische Mapping HR-Text → Material-Icon für den Bild-Joker.
///
/// Schlüssel werden vor dem Lookup lowercased. Datei kann frei ergänzt
/// werden, ohne Migration oder Datenrepo-Bump.
class VocabIcons {
  const VocabIcons._();

  static const Map<String, IconData> _map = {
    // Farben
    'crveno': Icons.brightness_1,
    'plavo': Icons.brightness_1,
    'zeleno': Icons.brightness_1,
    'žuto': Icons.brightness_1,
    'crno': Icons.brightness_1,
    'bijelo': Icons.brightness_1,
    'crvena': Icons.brightness_1,
    'plava': Icons.brightness_1,
    'zelena': Icons.brightness_1,
    'žuta': Icons.brightness_1,
    'crna': Icons.brightness_1,
    'bijela': Icons.brightness_1,
    'crven': Icons.brightness_1,
    'plav': Icons.brightness_1,
    'zelen': Icons.brightness_1,
    'žut': Icons.brightness_1,
    'crn': Icons.brightness_1,
    'bijel': Icons.brightness_1,
    'narančasto': Icons.brightness_1,
    'ljubičasto': Icons.brightness_1,
    'siva': Icons.brightness_1,
    'sivo': Icons.brightness_1,
    'roza': Icons.brightness_1,
    'smeđa': Icons.brightness_1,
    'smeđe': Icons.brightness_1,
    'boja': Icons.palette,
    // Verkehr / Fahrzeuge
    'auto': Icons.directions_car,
    'automobil': Icons.directions_car,
    'autobus': Icons.directions_bus,
    'vlak': Icons.directions_train,
    'avion': Icons.flight,
    'brod': Icons.directions_boat,
    'bicikl': Icons.directions_bike,
    'taksi': Icons.local_taxi,
    'kamion': Icons.local_shipping,
    'motor': Icons.two_wheeler,
    'tramvaj': Icons.tram,
    'cesta': Icons.add_road,
    'autocesta': Icons.add_road,
    'most': Icons.water,
    'benzinska': Icons.local_gas_station,
    'benzin': Icons.local_gas_station,
    'dizel': Icons.local_gas_station,
    'parking': Icons.local_parking,
    'kazna': Icons.gavel,
    'karta': Icons.confirmation_number,
    'guma': Icons.tire_repair,
    'volan': Icons.settings_input_component,
    // Gebäude / Orte
    'knjiga': Icons.book,
    'vrata': Icons.door_front_door,
    'prozor': Icons.window,
    'kuća': Icons.house,
    'stan': Icons.apartment,
    'škola': Icons.school,
    'bolnica': Icons.local_hospital,
    'banka': Icons.account_balance,
    'pošta': Icons.markunread_mailbox,
    'trgovina': Icons.store,
    'restoran': Icons.restaurant,
    'kavana': Icons.local_cafe,
    'kafić': Icons.local_cafe,
    'hotel': Icons.hotel,
    'crkva': Icons.church,
    'katedrala': Icons.church,
    'muzej': Icons.museum,
    'galerija': Icons.museum,
    'kazalište': Icons.theater_comedy,
    'park': Icons.park,
    'plaža': Icons.beach_access,
    'bazen': Icons.pool,
    'ljekarna': Icons.local_pharmacy,
    'apartman': Icons.apartment,
    'tržnica': Icons.storefront,
    'supermarket': Icons.local_grocery_store,
    // Möbel & Haushalt
    'stol': Icons.table_restaurant,
    'stolica': Icons.chair,
    'krevet': Icons.bed,
    'kuhinja': Icons.kitchen,
    'kupaonica': Icons.bathtub,
    'tuš': Icons.shower,
    'ključ': Icons.key,
    'lampa': Icons.light,
    'sat na zidu': Icons.schedule,
    // Tiere
    'pas': Icons.pets,
    'mačka': Icons.pets,
    'ptica': Icons.flutter_dash,
    'riba': Icons.set_meal,
    'konj': Icons.pets,
    'krava': Icons.pets,
    // Essen
    'kruh': Icons.bakery_dining,
    'sir': Icons.lunch_dining,
    'meso': Icons.kebab_dining,
    'jaje': Icons.egg,
    'voće': Icons.apple,
    'jabuka': Icons.apple,
    'banana': Icons.lunch_dining,
    'jagoda': Icons.spa,
    'naranča': Icons.circle,
    'krumpir': Icons.eco,
    'rajčica': Icons.circle,
    'salata': Icons.eco,
    'povrće': Icons.eco,
    'pizza': Icons.local_pizza,
    'sladoled': Icons.icecream,
    'kolač': Icons.cake,
    'tortica': Icons.cake,
    'čokolada': Icons.cookie,
    'juha': Icons.soup_kitchen,
    'doručak': Icons.breakfast_dining,
    'ručak': Icons.lunch_dining,
    'večera': Icons.dinner_dining,
    'jelo': Icons.restaurant_menu,
    'jelovnik': Icons.menu_book,
    'desert': Icons.cake,
    // Getränke
    'voda': Icons.water_drop,
    'kava': Icons.coffee,
    'čaj': Icons.emoji_food_beverage,
    'mlijeko': Icons.local_drink,
    'pivo': Icons.sports_bar,
    'vino': Icons.wine_bar,
    'sok': Icons.local_drink,
    'kapučino': Icons.coffee,
    'espreso': Icons.coffee,
    // Kleidung
    'cipele': Icons.snowshoeing,
    'majica': Icons.checkroom,
    'hlače': Icons.checkroom,
    'jakna': Icons.checkroom,
    'haljina': Icons.checkroom,
    'kaput': Icons.checkroom,
    'kapa': Icons.sports_baseball,
    'šal': Icons.checkroom,
    'rukavice': Icons.back_hand,
    'čarape': Icons.checkroom,
    'japanke': Icons.beach_access,
    // Wetter & Natur
    'sunce': Icons.wb_sunny,
    'kiša': Icons.umbrella,
    'snijeg': Icons.ac_unit,
    'vjetar': Icons.air,
    'oblak': Icons.cloud_queue,
    'magla': Icons.foggy,
    'munja': Icons.flash_on,
    'grom': Icons.flash_on,
    'oluja': Icons.thunderstorm,
    'more': Icons.waves,
    'rijeka': Icons.water,
    'jezero': Icons.water,
    'planina': Icons.terrain,
    'brdo': Icons.terrain,
    'šuma': Icons.forest,
    'drvo': Icons.park,
    'cvijet': Icons.local_florist,
    'trava': Icons.grass,
    'zvijezda': Icons.star,
    'mjesec': Icons.brightness_2,
    'nebo': Icons.cloud,
    'vatra': Icons.local_fire_department,
    'led': Icons.ac_unit,
    // Zeit
    'sat': Icons.schedule,
    'dan': Icons.today,
    'noć': Icons.nightlight_round,
    'jutro': Icons.wb_twilight,
    'popodne': Icons.wb_sunny,
    'večer': Icons.nights_stay,
    'tjedan': Icons.date_range,
    'mjesec dana': Icons.calendar_month,
    'godina': Icons.calendar_today,
    'minuta': Icons.timer,
    'sekunda': Icons.timer,
    'kalendar': Icons.calendar_month,
    // Schule / Büro / Tech
    'olovka': Icons.edit,
    'papir': Icons.description,
    'računalo': Icons.computer,
    'laptop': Icons.laptop,
    'mobitel': Icons.phone_iphone,
    'telefon': Icons.phone,
    'tipkovnica': Icons.keyboard,
    'miš': Icons.mouse,
    'internet': Icons.wifi,
    'e-pošta': Icons.email,
    'pismo': Icons.mail,
    'paket': Icons.local_shipping,
    // Familie
    'majka': Icons.face_3,
    'mama': Icons.face_3,
    'otac': Icons.face_6,
    'tata': Icons.face_6,
    'dijete': Icons.child_care,
    'beba': Icons.child_friendly,
    'brat': Icons.face_6,
    'sestra': Icons.face_3,
    'baka': Icons.elderly_woman,
    'djed': Icons.elderly,
    'sin': Icons.boy,
    'kći': Icons.girl,
    'dječak': Icons.boy,
    'djevojčica': Icons.girl,
    'obitelj': Icons.family_restroom,
    'prijatelj': Icons.group,
    'prijateljica': Icons.group,
    'muž': Icons.face_6,
    'žena': Icons.face_3,
    // Körper / Gesundheit
    'glava': Icons.face,
    'oko': Icons.visibility,
    'oči': Icons.visibility,
    'uho': Icons.hearing,
    'nos': Icons.air,
    'usta': Icons.sentiment_satisfied,
    'zub': Icons.medical_information,
    'jezik': Icons.translate,
    'ruka': Icons.back_hand,
    'noga': Icons.directions_walk,
    'srce': Icons.favorite,
    'prst': Icons.touch_app,
    'leđa': Icons.accessibility_new,
    'kosa': Icons.face_2,
    'bol': Icons.healing,
    'lijek': Icons.medication,
    'tableta': Icons.medication,
    'doktor': Icons.medical_services,
    'liječnik': Icons.medical_services,
    'sestra (med.)': Icons.medical_services,
    'temperatura': Icons.device_thermostat,
    'gripa': Icons.sick,
    'kašalj': Icons.sick,
    'glavobolja': Icons.psychology_alt,
    // Geld / Einkauf
    'novac': Icons.payments,
    'gotovina': Icons.payments,
    'kartica': Icons.credit_card,
    'bankomat': Icons.atm,
    'cijena': Icons.sell,
    'popust': Icons.local_offer,
    'akcija': Icons.local_offer,
    'račun': Icons.receipt_long,
    'blagajna': Icons.point_of_sale,
    'košarica': Icons.shopping_basket,
    'vrećica': Icons.shopping_bag,
    'kolica': Icons.shopping_cart,
    'euro': Icons.euro,
    'kuna': Icons.payments,
    // Hobbys / Sport / Reisen
    'glazba': Icons.music_note,
    'pjevanje': Icons.mic,
    'gitara': Icons.music_note,
    'film': Icons.movie,
    'fotografija': Icons.photo_camera,
    'fotoaparat': Icons.photo_camera,
    'nogomet': Icons.sports_soccer,
    'tenis': Icons.sports_tennis,
    'plivanje': Icons.pool,
    'trčanje': Icons.directions_run,
    'planinarenje': Icons.terrain,
    'putovanje': Icons.flight_takeoff,
    'kovčeg': Icons.luggage,
    'putovnica': Icons.contact_page,
    // Sonstiges Konkretes
    'ulica': Icons.signpost,
    'trg': Icons.location_city,
    'grad': Icons.location_city,
    'selo': Icons.holiday_village,
    'država': Icons.public,
    'svijet': Icons.public,
    'zastava': Icons.flag,
    'srcoliko': Icons.favorite,
    'poklon': Icons.card_giftcard,
    'svijeća': Icons.local_fire_department,
    'novine': Icons.newspaper,
    'kino': Icons.movie,
    'pjesma': Icons.music_note,
    'ples': Icons.music_video,
  };

  /// Liefert ein Icon, falls für den HR-Text ein Mapping existiert.
  /// Lookup ist case-insensitive auf der Eingabe.
  static IconData? lookup(String hrText) {
    final key = hrText.trim().toLowerCase();
    return _map[key];
  }

  static bool has(String hrText) => lookup(hrText) != null;

  /// Anzahl der Mappings (für Tests / Statistik).
  static int get size => _map.length;
}
